import React, { useState } from "react";
import MyMainMenu from "./../Components/NabBar";
import Head from "next/head";

async function handleSubmit(event) {
  event.preventDefault(); // prevent the form from reloading the page

  const response = await fetch("/api/schedule", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ name, time }), // send the name and time in the request body
  });

  const newEvent = await response.json(); // parse the response as JSON
  setSchedule([...schedule, newEvent]); // add the new event to the schedule array
  setName(""); // reset the name state
  setTime(""); // reset the time state
}

const About = () => {
  const [schedule, setSchedule] = useState([]); // initialize an empty schedule array
  const [name, setName] = useState(""); // initialize an empty name state
  const [time, setTime] = useState(""); // initialize an empty time state
  return (
    <>
      <Head>
        <title>listen coders-about</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <form onSubmit={handleSubmit}>
        <label>
          Event Name:
          <input
            type="text"
            value={name}
            onChange={(event) => setName(event.target.value)}
          />
        </label>
        <br />
        <label>
          Event Time:
          <input
            type="text"
            value={time}
            onChange={(event) => setTime(event.target.value)}
          />
        </label>
        <br />
        <button type="submit">Add Event</button>
        <ul>
          {schedule.map((event) => (
            <li key={event.id}>
              {event.name} at {event.time}
            </li>
          ))}
        </ul>
      </form>
    </>
  );
};

export default About;
