import Head from "next/head";
import HeroSec from "../Components/About/HeroSec";
import OurTeam from "../Components/About/OurTeam";
import styles from "../styles/about.module.css";

const about = () => {
  return (
    <>
      <Head>
        <title>about-listen coders</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <HeroSec />
        <OurTeam />
      </div>
    </>
  );
};

export default about;
