import Head from "next/head";
import React from "react";

const account = () => {
  return (
    <>
      <Head>
        <title>listen coders - account</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};

export default account;
