import MyMainMenu from "./../Components/NabBar";
import Head from 'next/head';


const contact = () => {
    return (
        <>
        <MyMainMenu />            
        <Head>
            <title>listen coders-contact</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        </>
    );
};

export default contact;