import Head from "next/head";
import Script from "next/script";
import styles from "../styles/contact.module.css";

const contact = () => {
  return (
    <>
      <Head>
        <title>listen coders-contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Script src="https://cdn.lordicon.com/fudrjiwc.js"></Script>

      <div className={styles.contact_main}>
        <div className={styles.contact_card}>
          <h1>If You Want To Know Anything</h1>
          <div className={styles.call_us}>
          <lord-icon
            src="https://cdn.lordicon.com/bjnaomnr.json"
            trigger="loop"
            style={{ width: "50px", height: "50px" }}
          ></lord-icon>{" "}
          <h1> +8801985-381288 </h1>
          </div>
          <div className={styles.email_us}>
          <lord-icon
            src="https://cdn.lordicon.com/gzmgulpl.json"
            trigger="loop"
            style={{ width: "50px", height: "50px" }}
            ></lord-icon>
            <h1>listencoders@gmail.com</h1>
          </div>
        </div>
      </div>
    </>
  );
};

export default contact;
