import Head from "next/head";
import styles from "../styles/courses.module.css";
import ClassesScheduler from "../Components/Courses/ClassesScheduler";
import LmsVideo from "../Components/Courses/LmsVideo";
import { Grid } from "@mui/material";
import { useState } from "react";

const courses = () => {
  const [clickedData, setClickData] = useState({});

  const getVideoChange = (e) => {
    setClickData(e)
  }
  console.log(clickedData)
  return (
    <>
      <Head>
        <title>listen coders-courses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Grid container className={styles.courseMain}>
        <Grid xs={12} sm={12} md={6}>
          <LmsVideo clickedData={clickedData}/>
        </Grid>
        <Grid xs={12} sm={12} md={6}>
          <ClassesScheduler getVideoChange={getVideoChange} />
        </Grid>
      </Grid>
    </>
  );
};

export default courses;
