import MyMainMenu from "./../Components/NabBar";
import Head from "next/head";
import Data from "./api/data.json";
import { useEffect } from "react";
import { useState } from "react";

const courses = () => {
  setInterval(() => {
    Data.map((dt) => {
      const dist = new Date(`${dt.uploadTime}`).getTime();
      const nowTime = new Date().getTime();
      console.log("dist", dist, "nowTime", nowTime);
      if (dist >= nowTime) {
        console.log("Fk ME");
      }
    });
  }, 1000);

  const dist = new Date("Dec 10, 2022 10:00:00").getTime();
  const nowTime = new Date().getTime();
  const def = dist - nowTime;

  const days = Math.floor(def / (100 * 60 * 60 * 24));
  const hours = Math.floor((def % (100 * 60 * 60 * 24)) / (1000 * 60 * 60));
  const minutes = Math.floor((def % (100 * 60 * 60)) / (1000 * 60));
  const seconds = Math.floor((def % (100 * 60)) / 1000);

  console.log(days, hours, minutes, seconds);

  return (
    <>
      <Head>
        <title>listen coders-courses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {Data.map((dt) => {
        return (
          <>
            <p>lol</p>
          </>
        );
      })}
    </>
  );
};

export default courses;
