import Head from "next/head";
import Header from "./../Components/Home/Header";
import YouTubeSe from "./../Components/Home/YouTubeSec";
import MissionVision from "./../Components/Home/MissionVision";
import FeaturedCourses from "./../Components/Home/FeaturedCourses";

export default function Home() {
  return (
    <>
      <Head>
        <title>listen coders-home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MissionVision />
      <YouTubeSe />
      <FeaturedCourses />
    </>
  );
}
