import Head from "next/head";
import ProfileDrawer from "../Components/ProfileDrawer/ProfileDrawer";

const profile = () => {
  return (
    <>
      <Head>
        <title>listen coders - profile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProfileDrawer /> 
    </>
  );
};

export default profile;
